version: "3"
services:
  s_angular:
    container_name: c_angular
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:4200
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - e_commerce

networks:
  e_commerce:
    name: e_commerce
